/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2S_Codec_audio.h"
#include "I2S_Codec_audio_PVT.h"
#include "POT_2_aliases.h"
#include "POT_2.h"
#include "RxDMA_dma.h"
#include "LCD.h"
#include "TxDMA_dma.h"
#include "SDO_aliases.h"
#include "SDO.h"
#include "SDI_aliases.h"
#include "SDI.h"
#include "L2_aliases.h"
#include "L2.h"
#include "Codec_en_aliases.h"
#include "Codec_en.h"
#include "SampleKlaar.h"
#include "L1_aliases.h"
#include "L1.h"
#include "LEDs.h"
#include "L0_aliases.h"
#include "L0.h"
#include "CLIP_LED_aliases.h"
#include "CLIP_LED.h"
#include "AudioCodecClk_aliases.h"
#include "AudioCodecClk.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C_Codec_control.h"
#include "I2C_Codec_control_PVT.h"
#include "VOL.h"
#include "POT_1_aliases.h"
#include "POT_1.h"
#include "I2S_EN.h"
#include "LINE.h"
#include "CLIP.h"
#include "L3_aliases.h"
#include "L3.h"
#include "S0_aliases.h"
#include "S0.h"
#include "S1_aliases.h"
#include "S1.h"
#include "S2_aliases.h"
#include "S2.h"
#include "S3_aliases.h"
#include "S3.h"
#include "KNOP.h"
#include "KNOP_TOGGLE.h"
#include "Debounce.h"
#include "SampleVraag.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "I2C_Codec_control_IntClock.h"
#include "VOL_IRQ.h"
#include "VOL_theACLK.h"
#include "LINE_IRQ.h"
#include "LINE_theACLK.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

